apply plugin: 'com.android.application'

android {
    compileSdkVersion  = 37
    defaultConfig {
        applicationId = "nz.mentalinc.episodeWatcher"
        minSdk = 33
        targetSdk 37
        versionCode = 41
        versionName = '1.9.1'

        missingDimensionStrategy   'react-native-camera', 'general'

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    signingConfigs {
        debug {
            storeFile file('../keystore/debug.keystore')
        }
        release {
            storeFile file('../keystore/dvr-android.keystore')
            storePassword System.getenv("storepwd")
            keyAlias System.getenv("keyalias")
            keyPassword System.getenv("keypwd")
        }
    }
    buildTypes {
        debug {
            versionNameSuffix '- DEBUG'
            applicationIdSuffix ".debug"
            signingConfig = signingConfigs.debug
        }
        release {
            minifyEnabled false
           // proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    productFlavors {
    }
    //buildToolsVersion '34.0.0'
    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
    namespace = 'nz.mentalinc.watcher'
    buildToolsVersion = '36.1.0'
}


dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.room:room-runtime:2.8.4'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    annotationProcessor 'androidx.room:room-compiler:2.8.4'
    // For Kotlin use kapt instead of annotationProcessor
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.room:room-testing:2.8.4'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.12.0'
    androidTestImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
    implementation 'androidx.core:core:1.18.0'


    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.annotation:annotation:1.10.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    implementation 'com.github.bumptech.glide:glide:5.0.7'
    sonar {
        properties {
            property "sonar.projectKey", "MyEpispodes"
            property "sonar.host.url", "http://192.168.2.94:9000"  // URL of your SonarQube server
            property "sonar.projectName", "MyEpispodes"
            property "sonar.organization", "mentalinc"
            property "sonar.java.binaries", "$buildDir\\intermediates\\javac"

        }
    }
}
